version: '3.3'
services:
  mapledocs-postgresql:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  mapledocs-mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  mapledocs-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=mapledocs-elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
  mapledocs-logstash:
    image: docker.elastic.co/logstash/logstash:7.7.0
    container_name: logstash
    volumes:
      - ~/logstash-pipeline/:/usr/share/logstash/pipeline/:ro
    command: bash -c "logstash-plugin install logstash-input-mongodb && logstash"
    depends_on:
      - mapledocs-elasticsearch
  mapledocs-app:
    image: mapledocs-app
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - mapledocs-postgresql
      - mapledocs-mongodb
      - mapledocs-logstash

volumes:
  mongodb_data_container:
